# Generated by Django 6.0.4 on 2026-05-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ONCOLOGIST', 'Oncologist'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('BILLING', 'Billing Officer'), ('RECEPTIONIST', 'Receptionist'), ('LAB_TECH', 'Lab Technician'), ('RADIOLOGIST', 'Radiologist'), ('ADMIN', 'HMS Admin'), ('STAFF', 'General Staff'), ('PATIENT', 'Patient'), ('CLIENT', 'Client')], default='RECEPTIONIST', max_length=20),
        ),
    ]
