# Generated by Django 6.0.4 on 2026-04-29 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('stock_qty', models.IntegerField(default=0)),
                ('min_threshold', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registry_no', models.CharField(help_text='Cancer Registry Number', max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cancer_type', models.CharField(max_length=100)),
                ('staging', models.JSONField(default=dict, help_text="TNM Staging (e.g., {'T': 1, 'N': 0, 'M': 0})")),
                ('biomarkers', models.JSONField(default=dict, help_text='ER, PR, HER2, etc.')),
                ('ecog_status', models.IntegerField(default=0, help_text='0-5 scale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('result_value', models.CharField(max_length=50)),
                ('is_critical', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('insurance_claim_status', models.CharField(default='Pending', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('total_cycles', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.patient')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='ChemoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.IntegerField()),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('toxicity_score', models.IntegerField(default=0, help_text='CTCAE grade')),
                ('notes', models.TextField(blank=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.treatment')),
            ],
        ),
    ]
