# Generated by Django 6.0.4 on 2026-05-12 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('strength', models.CharField(help_text='e.g., 500mg, 10mg/ml', max_length=100)),
                ('unit_type', models.CharField(default='vial', help_text='e.g., vial, tablet, bottle', max_length=50)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Minimum threshold before requisition')),
                ('expiry_date', models.DateField(null=True)),
                ('selling_price_kes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('store_location', models.CharField(choices=[('main', 'Main Bulk Store'), ('pharmacy', 'Pharmacy Shop')], default='pharmacy', max_length=20)),
                ('storage_requirements', models.TextField(blank=True, help_text='e.g., Refrigerate 2-8°C')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Cytotoxic/Hazardous')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(default='General', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=5)),
                ('unit', models.CharField(default='Units', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('registry_no', models.CharField(help_text='National ID or Passport Number', max_length=50, unique=True, verbose_name='ID Number')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cancer_type', models.CharField(default='General', max_length=255)),
                ('staging', models.CharField(blank=True, max_length=50)),
                ('ecog_status', models.IntegerField(default=0, help_text='0-5 Performance Status')),
                ('biomarkers', models.TextField(blank=True, help_text='Relevant genetic or protein markers')),
                ('insurance_type', models.CharField(default='CASH', max_length=50)),
                ('insurance_no', models.CharField(blank=True, max_length=100)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('last_verification_date', models.DateTimeField(blank=True, null=True)),
                ('benefit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_cycles', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_patient_name', models.CharField(blank=True, help_text='For preliminary registration', max_length=255)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('visit_type', models.CharField(choices=[('NEW', 'New Visit'), ('SUBSEQUENT', 'Subsequent Visit')], default='NEW', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked-in'), ('WAITING_TRIAGE', 'Waiting Triage'), ('TRIAGED', 'Triaged'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practitioner', models.ForeignKey(limit_choices_to={'role__in': ['ONCOLOGIST', 'SURGEON', 'HEMATOLOGIST', 'PSYCHOLOGIST', 'NURSE', 'LAB_TECH', 'RADIOLOGIST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
                ('findings', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('CONSULT', 'Consultation'), ('PROGRESS', 'Progress')], max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='CASH', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('billing_officer', models.ForeignKey(limit_choices_to={'role': 'BILLING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('current_station', models.CharField(choices=[('REGISTRATION', 'Registration'), ('TRIAGE', 'Triage Station'), ('DOCTOR', 'Consultation Room'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology Room'), ('PSYCHOLOGY', 'Psychology Room'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing/Discharge')], default='TRIAGE', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('UNDER_CONSULTATION', 'Under Consultation'), ('AWAITING_MEDICATION', 'Awaiting Medication'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal Priority'), ('HIGH', 'High Priority'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('result_value', models.CharField(max_length=255)),
                ('is_critical', models.BooleanField(default=False)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'LAB_TECH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.queue')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('remaining_stock', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.labinventoryitem')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('oncologist', models.ForeignKey(limit_choices_to={'role': 'ONCOLOGIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='core.patient')),
                ('protocol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='ChemoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cycle_no', models.IntegerField()),
                ('pre_auth_code', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='°C', max_digits=4)),
                ('systolic_bp', models.PositiveIntegerField(help_text='mmHg')),
                ('diastolic_bp', models.PositiveIntegerField(help_text='mmHg')),
                ('heart_rate', models.PositiveIntegerField(help_text='bpm')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='cm', max_digits=5)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Oxygen Saturation %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.patient')),
                ('queue_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.queue')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
