# Generated by Django 6.0.4 on 2026-05-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrecord',
            name='insurance',
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.insurancecompany'),
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('INSURANCE', 'Insurance')], default='CASH', max_length=15),
        ),
    ]
