# Generated by Django 6.0.4 on 2026-06-12 03:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='clinical_notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='drug_id',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='quantity_prescribed',
        ),
        migrations.AddField(
            model_name='prescription',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='cycle_no',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dose_adjustment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='meta_extensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_status',
            field=models.CharField(default='Pending Dispense', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribe_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='total_cycles',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='calc_factor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='diluent',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.drug'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='factor_value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='stage',
            field=models.CharField(choices=[('PRE_CHEMO', 'Pre-Chemotherapy'), ('CHEMO', 'Chemotherapy Core Orders'), ('POST_CHEMO', 'Post-Chemotherapy Take Home')], default='CHEMO', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='protocol',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.queue'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
