# Generated by Django 6.0.4 on 2026-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='charge_type',
            field=models.CharField(choices=[('TRIGGERED', 'Triggered Event (Station Check-In)'), ('DAILY_RECURRING', 'Daily Recurring (Midnight Run)'), ('VARIABLE', 'Variable Entry (Manual input or Inventory)')], db_index=True, default='TRIGGERED', max_length=20),
        ),
    ]
