# Generated by Django 6.0.4 on 2026-05-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalsign',
            options={'ordering': ['-created_at']},
        ),
    ]
