# Generated by Django 6.0.4 on 2026-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='parameters',
        ),
        migrations.AddField(
            model_name='labresult',
            name='bg_abo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='bg_compatibility',
            field=models.CharField(blank=True, choices=[('Compatible', 'Compatible'), ('Incompatible', 'Incompatible')], max_length=20, null=True, verbose_name='Crossmatch'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='bg_rhesus',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive (+)'), ('Negative', 'Negative (-)')], max_length=15, null=True, verbose_name='Rhesus Factor'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='cbc_hb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hb (g/dL)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='cbc_mcv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='MCV (fL)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='cbc_neut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Neut (x10³/µL)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='cbc_plt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Plt (x10³/µL)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='cbc_wbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='WBC (x10³/µL)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lft_albumin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ALB (g/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lft_alp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ALP (U/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lft_alt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ALT (U/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lft_ast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AST (U/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lft_dbil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='D.BIL (µmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='lft_tbil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='T.BIL (µmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='malaria_mps',
            field=models.CharField(blank=True, choices=[('Not Seen', 'Not Seen'), ('Positive', 'Positive (+)')], max_length=20, null=True, verbose_name='MPS Status'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='malaria_species',
            field=models.CharField(blank=True, choices=[('P. falciparum', 'P. falciparum'), ('P. vivax', 'P. vivax'), ('N/A', 'N/A')], max_length=40, null=True, verbose_name='Parasite Species'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='psa_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total PSA (ng/mL)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='ue_creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cr (µmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='ue_k',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='K+ (mmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='ue_na',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Na+ (mmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='ue_urea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Urea (mmol/L)'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='urine_blood',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='urine_clarity',
            field=models.CharField(blank=True, choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Turbid', 'Turbid')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='urine_color',
            field=models.CharField(blank=True, choices=[('Straw', 'Straw'), ('Yellow', 'Yellow'), ('Amber', 'Amber'), ('Red', 'Red')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='urine_glucose',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Trace', 'Trace'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='urine_nitrites',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='urine_protein',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Trace', 'Trace'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+')], max_length=20, null=True),
        ),
    ]
