# Generated by Django 6.0.4 on 2026-05-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(help_text='e.g., Oxaliplatin, Doxorubicin', max_length=150)),
                ('base_dose', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('unit', models.CharField(choices=[('mg/m²', 'mg/m²'), ('mg/kg', 'mg/kg'), ('AUC', 'Target AUC'), ('mg (Fixed)', 'mg (Fixed)')], default='mg/m²', max_length=20)),
                ('route', models.CharField(choices=[('IV Infusion', 'Intravenous Infusion'), ('IV Push', 'IV Push'), ('PO (Oral)', 'PO (Oral Pill)')], default='IV Infusion', max_length=50)),
                ('administration_day', models.CharField(default='Day 1', help_text='e.g., Day 1, Days 1-2', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(help_text='e.g., FOLFOX6, AC-T', max_length=100, unique=True)),
                ('cancer_type', models.CharField(choices=[('Breast Cancer', 'Breast Cancer'), ('Colorectal Cancer', 'Colorectal Cancer'), ('Prostate Cancer', 'Prostate Cancer'), ('Lung Cancer', 'Lung Cancer')], max_length=100)),
                ('stages', models.JSONField(default=list, help_text="e.g., ['Stage III', 'Stage IV']")),
                ('biomarkers', models.JSONField(default=list, help_text="e.g., ['KRAS Wild-Type', 'HER2 Negative']")),
                ('clinical_signs', models.TextField(blank=True, help_text='Warnings/Nadir notes for clinicians', null=True)),
                ('total_cycles', models.PositiveIntegerField(default=6)),
                ('days_per_cycle', models.PositiveIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugGuardrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('CrCl (Renal)', 'CrCl (Renal Function)'), ('Total Bilirubin', 'Total Bilirubin (Hepatic)'), ('ANC (Neutrophils)', 'ANC (Absolute Neutrophils)'), ('Platelets', 'Platelets (Hematological)')], max_length=50)),
                ('operator', models.CharField(choices=[('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>=')], max_length=5)),
                ('value', models.CharField(help_text='Laboratory limit threshold numerical limit value', max_length=20)),
                ('action', models.CharField(choices=[('REDUCE_PCT', 'Reduce Dosage By'), ('BLOCK', 'BLOCK REGIMEN / HALT')], default='REDUCE_PCT', max_length=20)),
                ('action_value', models.PositiveIntegerField(blank=True, help_text='Percentage to drop if action is REDUCE_PCT', null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.protocoldrug')),
            ],
        ),
        migrations.AddField(
            model_name='protocoldrug',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='core.protocolmaster'),
        ),
    ]
