# Generated by Django 6.0.4 on 2026-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_available', models.IntegerField(default=0)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('LAB', 'Laboratory'), ('NURSING', 'Nursing'), ('RADIOLOGY', 'Radiology'), ('ADMIN', 'General Admin')], max_length=50)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
