# Generated by Django 6.0.4 on 2026-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ecog_status',
            field=models.IntegerField(default=0, help_text='0-5 Performance Status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_type',
            field=models.CharField(default='CASH', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
