# Generated by Django 6.0.4 on 2026-06-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clinical_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
