# Generated by Django 6.0.4 on 2026-05-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_ecog_status_patient_insurance_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=50),
        ),
        migrations.AddField(
            model_name='chemosession',
            name='pre_auth_code',
            field=models.CharField(blank=True, help_text='SHA/NHIF Pre-auth number', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='benefit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemosession',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
