# Generated by Django 6.0.4 on 2026-05-31 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vitalsign_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.cancersite')),
            ],
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_cycles', models.IntegerField(default=6)),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimens', to='core.cancertype')),
            ],
        ),
        migrations.CreateModel(
            name='RegimenDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_value', models.CharField(blank=True, max_length=50)),
                ('metric_unit', models.CharField(default='mg/m²', max_length=50)),
                ('route_pathway', models.CharField(default='IV Infusion', max_length=100)),
                ('cycle_cost_kes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='core.regimen')),
            ],
        ),
    ]
