# Generated by Django 6.0.4 on 2026-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260615_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
