# Generated by Django 6.0.4 on 2026-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrecord',
            name='is_returning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationrecord',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
