# Generated by Django 6.0.4 on 2026-06-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_charge_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientbillableitem',
            options={},
        ),
        migrations.RenameField(
            model_name='patientbillableitem',
            old_name='created_at',
            new_name='incurred_at',
        ),
        migrations.RenameField(
            model_name='patientbillableitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='billing_status',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='ordered_by',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='price_snap',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='service_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='service_sku_snapshot',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='station_charged',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='patientbillableitem',
            name='visit',
        ),
        migrations.AddField(
            model_name='patientbillableitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billable_items', to='core.drug'),
        ),
        migrations.AddField(
            model_name='patientbillableitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientbillableitem',
            name='name',
            field=models.CharField(default=1, help_text='Captured name at the moment of entry execution', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientbillableitem',
            name='station',
            field=models.CharField(choices=[('Consultation', 'Oncology (Consultation Room)'), ('Laboratory', 'Laboratory'), ('Radiology', 'Radiology & Imaging'), ('Nursing', 'Nursing & Procedures'), ('Pharmacy', 'Pharmacy'), ('Psychology', 'Counselling Psychology')], default='Consultation', max_length=30),
        ),
        migrations.AddField(
            model_name='patientbillableitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='patientbillableitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billable_items', to='core.service'),
        ),
        migrations.CreateModel(
            name='PatientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid Draft'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Settled'), ('INSURANCE_PENDING', 'Awaiting Insurance Pre-Auth Clear')], default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.registrationrecord')),
            ],
        ),
        migrations.AddField(
            model_name='patientbillableitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.patientinvoice'),
            preserve_default=False,
        ),
    ]
