# Generated by Django 6.0.4 on 2026-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prescription_clinical_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinventoryitem',
            name='category',
            field=models.CharField(choices=[('Chemicals', 'Chemicals'), ('Consumables', 'Consumables'), ('Reagents', 'Reagents'), ('Microscopy', 'Microscopy')], default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacystockcatalogitem',
            name='formulation',
            field=models.CharField(help_text='e.g., Tablets, Vials, Syrup', max_length=255),
        ),
        migrations.AlterField(
            model_name='regimen',
            name='name',
            field=models.CharField(help_text='Oncology protocol name', max_length=255),
        ),
        migrations.AlterField(
            model_name='regimendrug',
            name='route_pathway',
            field=models.CharField(default='IV Infusion', max_length=255),
        ),
    ]
