# Generated by Django 6.0.4 on 2026-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Oral Suspension'), ('VIAL', 'Vial (Liquid/Powder for Injection)'), ('AMP_INJ', 'Ampoule (Injection)'), ('INF_BAG', 'Infusion Bag (Premixed Cytotoxic/Hydration)'), ('OINTMENT', 'Ointment / Cream'), ('PATCH', 'Transdermal Patch (e.g., Fentanyl)'), ('SUPPOSITORY', 'Suppository (e.g., antiemetics)')], max_length=20, null=True),
        ),
    ]
