# Generated by Django 6.0.4 on 2026-05-16 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('medical_record_no', models.CharField(max_length=100, unique=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('current_stage', models.CharField(choices=[('DENIAL', 'Denial & Shock'), ('ANGER', 'Anger & Resistance'), ('BARGAINING', 'Bargaining Process'), ('DEPRESSION', 'Depression'), ('ACCEPTANCE', 'Acceptance & Compliance')], default='DENIAL', max_length=50)),
                ('status', models.CharField(choices=[('IN_THERAPY', 'In Therapy'), ('BAD_NEWS_DEBRIEF', 'Bad News Debrief'), ('SUPPORT_GROUP', 'Support Group'), ('LOST_TO_FOLLOW_UP', 'Lost to Follow Up'), ('CASE_CLOSED', 'Case Closed')], default='IN_THERAPY', max_length=50)),
                ('location_department', models.CharField(choices=[('CHEMO_SUITE', 'Chemo Suite'), ('PHARMACY_REFILL', 'Pharmacy Refill'), ('RADIOLOGY_REF', 'Radiology Reference'), ('LABORATORY', 'Laboratory'), ('WARDS', 'In-Patient Wards')], default='CHEMO_SUITE', max_length=50)),
                ('consent_form_signed', models.BooleanField(default=False)),
                ('initial_intake_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BereavementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
                ('support_status', models.CharField(choices=[('ACTIVE_GRIEF', 'Active Grief Work'), ('BEREAVEMENT', 'Bereavement Support'), ('PALLIATIVE_RECONCILIATION', 'Palliative Reconciliation'), ('MONITORING_CLOSED', 'Monitoring Closed')], default='ACTIVE_GRIEF', max_length=50)),
                ('total_sessions_conducted', models.IntegerField(default=0)),
                ('last_contact_date', models.DateField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.psychologyenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('clinical_notes', models.TextField()),
                ('is_synced_with_hro', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.psychologyenrollment')),
            ],
        ),
    ]
