# Generated by Django 6.0.4 on 2026-05-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_registrationrecord_insurance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dept', models.CharField(choices=[('ONC', 'Oncology Center'), ('LAB', 'Laboratory'), ('RAD', 'Radiology & Imaging'), ('NUR', 'Nursing & Procedures'), ('PSY', 'Counselling Psychology'), ('PHA', 'Pharmacy')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base selling price in KES', max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrationrecord',
            name='queue_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='PatientBillableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_sku_snapshot', models.CharField(max_length=50)),
                ('service_name_snapshot', models.CharField(max_length=255)),
                ('station_charged', models.CharField(choices=[('REGISTRATION', 'Registration'), ('TRIAGE', 'Triage Station'), ('DOCTOR', 'Consultation Room'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology Room'), ('PSYCHOLOGY', 'Psychology Room'), ('PHARMACY', 'Pharmacy')], max_length=20)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price_snap', models.DecimalField(decimal_places=2, help_text='Price snapshot at point of care', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('billing_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_charges', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billable_items', to='core.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billable_items', to='core.registrationrecord')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billed_instances', to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
