# Generated by Django 6.0.4 on 2026-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_labinventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimendrug',
            name='base_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='regimendrug',
            name='metric_unit',
            field=models.CharField(default='mg/m²', max_length=255),
        ),
    ]
