# Generated by Django 6.0.4 on 2026-05-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cancersite_cancertype_regimen_regimendrug'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='applicable_stages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='protocol',
            name='cancer_type_id',
            field=models.IntegerField(default=1, help_text='ID of the specific cancer variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='primary_site_id',
            field=models.IntegerField(default=1, help_text='ID of the matching primary anatomical site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='regimen_template_id',
            field=models.IntegerField(blank=True, help_text='ID of blueprint template if pre-populated', null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='total_cost_per_cycle',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='name',
            field=models.CharField(help_text='e.g., TC, CMF, FOLFOX', max_length=255),
        ),
        migrations.CreateModel(
            name='ProtocolIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('base_dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(help_text='e.g., mg/m², mg, mcg', max_length=50)),
                ('route_of_administration', models.CharField(help_text='e.g., IV Infusion, Oral', max_length=100)),
                ('cost_per_cycle', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.protocol')),
            ],
        ),
    ]
