# Generated by Django 6.0.4 on 2026-05-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_psychologyenrollment_bereavementlog_sessionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('SCREENING_CAMP', 'Screening Camp'), ('COMMUNITY_BARAZA', 'Community Baraza'), ('MEDIA_DRIVE', 'Media Drive'), ('DIGITAL_OUTREACH', 'Digital Outreach')], default='SCREENING_CAMP', max_length=40)),
                ('target_region_location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('estimated_attendance', models.PositiveIntegerField(default=0)),
                ('actual_turnout', models.PositiveIntegerField(default=0)),
                ('patients_referred_to_salama', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('notes_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_or_doctor_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('PRIVATE_CLINIC', 'Private Medical Practitioner / Clinic'), ('COUNTY_HOSPITAL', 'County Referral Hospital Unit'), ('CHV_NETWORK', 'Community Health Volunteer Network'), ('ALUMNI_PATIENT', 'Patient Advocate / Survivor')], default='PRIVATE_CLINIC', max_length=40)),
                ('contact_phone', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_base', models.CharField(max_length=255)),
                ('total_patients_referred', models.PositiveIntegerField(default=0)),
                ('is_active_engagement', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('target_platform', models.CharField(choices=[('FACEBOOK', 'Facebook Page'), ('INSTAGRAM', 'Instagram Business'), ('VERNACULAR_RADIO', 'Vernacular Radio Log')], default='FACEBOOK', max_length=30)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('consent_verified', models.BooleanField(default=False)),
                ('medical_signoff', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
