# Generated by Django 6.0.4 on 2026-06-04 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patientbillableitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_us_carotid', models.BooleanField(default=False, verbose_name='U/S Carotid Doppler/Duplex')),
                ('has_us_duplex_low_ext', models.BooleanField(default=False, verbose_name='U/S Duplex Scan Low Ext Artery R/O Pseudo')),
                ('has_us_venous_ext', models.BooleanField(default=False, verbose_name='U/S Venous Duplex/Extremity')),
                ('has_us_venous_unila', models.BooleanField(default=False, verbose_name='U/S Venous Duplex/Extrm/Unila')),
                ('has_us_doppler_abd_pel', models.BooleanField(default=False, verbose_name='U/S Doppler, Abdominal/Pelvic')),
                ('has_us_limited_duplex', models.BooleanField(default=False, verbose_name='U/S Limited Study Duplex Scan')),
                ('has_us_hemodialysis', models.BooleanField(default=False, verbose_name='U/S Duplex Scan of Hemodialysis')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('COMPLETED', 'Results Ready')], default='PENDING', max_length=20)),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes/Clinical indications from the ordering clinician', null=True)),
                ('radiologist_report', models.TextField(blank=True, help_text='Official scan diagnostic summary from the radiologist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='core.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_imaging', to='core.registrationrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_name', models.CharField(choices=[('US_CAROTID', 'U/S Carotid Doppler/Duplex'), ('US_DUPLEX_LOW_EXT', 'U/S Duplex Scan Low Ext Artery R/O Pseudo'), ('US_VENOUS_EXT', 'U/S Venous Duplex/Extremity'), ('US_VENOUS_UNILA', 'U/S Venous Duplex/Extrm/Unila'), ('US_DOPPLER_ABD_PEL', 'U/S Doppler, Abdominal/Pelvic'), ('US_LIMITED_DUPLEX', 'U/S Limited Study Duplex Scan'), ('US_HEMODIALYSIS', 'U/S Duplex Scan of Hemodialysis')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Result Ready')], default='PENDING', max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('findings', models.TextField(blank=True, help_text='Detailed anatomical observations made during the ultrasound scan.', null=True)),
                ('impression', models.TextField(blank=True, help_text='The core clinical conclusion/diagnosis. What the doctor needs to know immediately.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imaging_order', models.ForeignKey(blank=True, help_text='The originating clinical instruction record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.imagingorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_history', to='core.patient')),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'RADIOLOGIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='core.registrationrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Key frame or annotated ultrasound snapshot graph', upload_to='radiology/attachments/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text="Optional description, e.g., 'Right carotid artery bifurcation showing velocity'", max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imaging_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.imagingresult')),
            ],
        ),
    ]
