# Generated by Django 6.0.4 on 2026-05-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_queue_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='appointment',
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.registrationrecord'),
        ),
    ]
