# Generated by Django 6.0.4 on 2026-06-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patientinvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='dispatch_batch',
            field=models.ForeignKey(blank=True, help_text='The batch envelope containing this claim when sent to the insurer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.claimdispatchbatch'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='patient_invoice',
            field=models.OneToOneField(blank=True, help_text='The source patient invoice invoice tracking session data.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claim', to='core.patientinvoice'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='remittance_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_claims', to='core.remittancebatch'),
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PRE_AUTH', 'Pre-Authorization Form'), ('BIOPSY', 'Histopathology / Biopsy Report'), ('IMAGING', 'Radiology Report (CT/PET/MRI)'), ('TREATMENT_PLAN', 'Oncologist Treatment Protocol Summary'), ('NURSING_CHART', 'Signed Chemotherapy Administration Log'), ('INVOICE', 'Itemized Detailed Ledger Statement'), ('OTHER', 'Supporting Lab/Clinical Document')], max_length=30)),
                ('file', models.FileField(help_text='Upload scanned PDF or Image of the document', upload_to='claim_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='e.g. Biopsy report from Lancet Log', max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.insuranceclaim')),
            ],
        ),
    ]
