# Generated by Django 6.0.4 on 2026-05-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outreachcampaign_referralpartner_socialmediapost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('POSTERS_PRINTING', 'Posters & Printing Materials'), ('SOCIAL_ADS', 'Social Media Advertising (Meta/Google)'), ('LOGISTICS_TRAVEL', 'Field Transport & Fuel Logistics'), ('MEDIA_AIRTIME', 'Radio Airtime & PR Sponsorships'), ('MISC_SUPPLIES', 'Miscellaneous Camp Supplies')], max_length=50)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('justification_notes', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Finance Review'), ('APPROVED', 'Funds Disbursed'), ('REJECTED', 'Requisition Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(help_text='Link this budget request to an active outreach program line', on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='core.outreachcampaign')),
            ],
        ),
    ]
