# Generated by Django 6.0.4 on 2026-05-13 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_vitalsign_appointment_vitalsign_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='clinicalnote',
            old_name='doctor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='test_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='queue_entry',
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='core.registrationrecord'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reference_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ordered'), ('COLLECTED', 'Sample Collected'), ('COMPLETED', 'Result Ready')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='labresult',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='core.registrationrecord'),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='note_type',
            field=models.CharField(choices=[('TRIAGE', 'Triage Assessment'), ('ONCOLOGY', 'Oncology Consultation'), ('LAB_REPORT', 'Laboratory Summary'), ('PHARMACY', 'Pharmacist Notes'), ('GENERAL', 'General Progress Note')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_history', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(choices=[('CBC', 'Full Blood Count (CBC)'), ('PSA', 'Prostate Specific Antigen (PSA)'), ('UE', 'Urea & Electrolytes'), ('LFT', 'Liver Function Test (LFT)'), ('URINALYSIS', 'Urinalysis'), ('BG_CROSS', 'Blood Group & Cross Match'), ('MALARIA_BS', 'Blood Slide for Malaria')], max_length=50),
        ),
    ]
