# Generated by Django 6.0.4 on 2026-05-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chemosession_pre_auth_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='diastolic_bp',
            field=models.PositiveIntegerField(help_text='mmHg', null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='systolic_bp',
            field=models.PositiveIntegerField(help_text='mmHg', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cancer_type',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
