# Generated by Django 6.0.4 on 2026-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_regimendrug_base_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Protocol remarks, titration exceptions, or toxicity justifications.', null=True),
        ),
    ]
