# Generated by Django 6.0.4 on 2026-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_protocol_applicable_stages_protocol_cancer_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='cycle_duration_days',
            field=models.IntegerField(default=21, help_text='Duration of a single treatment cycle (days)'),
        ),
    ]
