# Generated by Django 6.0.4 on 2026-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_insuranceclaim_dispatch_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_record_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registry_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationrecord',
            name='health_record_number',
            field=models.CharField(db_index=True, editable=False, max_length=30),
        ),
    ]
