# Generated by Django 6.0.4 on 2026-06-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagingorder_imagingresult_imagingattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='NurseServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_wound_dressing', models.BooleanField(default=False, verbose_name='Wound Dressing')),
                ('has_catheter_change', models.BooleanField(default=False, verbose_name='Catheter Change')),
                ('has_pelvic_screening', models.BooleanField(default=False, verbose_name='Pelvic Screening')),
                ('total_estimated_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_orders', to='core.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_orders', to='core.registrationrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
