# Generated by Django 6.0.4 on 2026-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_prescription_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
