# Generated by Django 6.0.4 on 2026-05-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_clinicalnote_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='reference_range',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='result_value',
        ),
        migrations.AddField(
            model_name='labresult',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Structured results based on test type'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='technician_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Sample Collected'), ('COMPLETED', 'Result Ready')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(choices=[('CBC', 'Full Blood Count (CBC)'), ('PSA', 'Prostate Specific Antigen (PSA)'), ('UE', 'Urea & Electrolytes (U&E)'), ('LFT', 'Liver Function Test (LFT)'), ('URINALYSIS', 'Urinalysis (Routine)'), ('BG_CROSS', 'Blood Group & Cross Match'), ('MALARIA_BS', 'Blood Slide for Malaria')], max_length=50),
        ),
    ]
