# Generated by Django 6.0.4 on 2026-06-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient_health_record_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='token_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
