# Generated by Django 6.0.4 on 2026-05-06 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_vitalsign_blood_pressure_drug_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='manual_patient_name',
            field=models.CharField(blank=True, help_text='For new registrations', max_length=255),
        ),
        migrations.AlterField(
            model_name='chemosession',
            name='pre_auth_code',
            field=models.CharField(blank=True, help_text='Insurance pre-authorization', max_length=100),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='diastolic_bp',
            field=models.PositiveIntegerField(default=80, help_text='mmHg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='height',
            field=models.DecimalField(decimal_places=2, default=120, help_text='cm', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='systolic_bp',
            field=models.PositiveIntegerField(default=170, help_text='mmHg'),
            preserve_default=False,
        ),
    ]
