# Generated by Django 6.0.4 on 2026-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_protocol_cycle_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_site', models.CharField(choices=[('BREAST', 'Breast'), ('HEAD & NECK', 'Head & Neck'), ('BONE & NECK', 'Bone & Neck'), ('BRAIN TUMOURS', 'Brain Tumours'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('LUNG', 'Lung'), ('UROLOGICAL', 'Urological'), ('KAPOSI SARCOMA', 'Kaposi Sarcoma'), ('ADULT HAEMATOLOGICAL', 'Adult Haematological'), ('GYNAECOLOGICAL', 'Gynaecological'), ('LEUKEMIA', 'Leukemia')], db_index=True, max_length=50)),
                ('code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Anatomical Diagnosis Mapping',
                'verbose_name_plural': 'Anatomical Diagnosis Mappings',
            },
        ),
    ]
