# Generated by Django 6.0.4 on 2026-05-14 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_labresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('LAB', 'Laboratory'), ('NURSE', 'Nursing'), ('PHARMACY', 'Pharmacy'), ('RADIOLOGY', 'Radiology'), ('ONCOLOGY', 'Oncology Clinic'), ('MARKETING', 'Marketing/Admin')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ORDERED', 'Order Placed'), ('RECEIVED', 'Partially Received'), ('COMPLETED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('clinical_justification', models.TextField(blank=True, null=True)),
                ('accountant_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='Units', max_length=20)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.labinventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.requisition')),
            ],
        ),
    ]
