# Generated by Django 6.0.4 on 2026-06-01 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_icd10diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10diagnosis',
            name='primary_site',
            field=models.CharField(choices=[('BREAST', 'Breast'), ('HEAD & NECK', 'Head & Neck'), ('BONE & NECK', 'Bone & Neck'), ('BRAIN TUMOURS', 'Brain Tumours'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('LUNG', 'Lung'), ('UROLOGICAL', 'Urological'), ('KAPOSI SARCOMA', 'Kaposi Sarcoma'), ('GYNAECOLOGICAL', 'Gynaecological'), ('LEUKEMIA', 'Leukemia')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_site', models.CharField(choices=[('BREAST', 'Breast'), ('HEAD & NECK', 'Head & Neck'), ('BONE & NECK', 'Bone & Neck'), ('BRAIN TUMOURS', 'Brain Tumours'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('LUNG', 'Lung'), ('UROLOGICAL', 'Urological'), ('KAPOSI SARCOMA', 'Kaposi Sarcoma'), ('GYNAECOLOGICAL', 'Gynaecological'), ('LEUKEMIA', 'Leukemia')], db_index=True, max_length=50)),
                ('icd10_code', models.CharField(db_index=True, max_length=15)),
                ('icd10_description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.registrationrecord')),
            ],
            options={
                'verbose_name': 'Patient Diagnosis Record',
                'verbose_name_plural': 'Patient Diagnosis Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
