# Generated by Django 6.0.4 on 2026-05-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_amount_bill_total_amount_bill_appointment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='manual_patient_name',
            field=models.CharField(blank=True, help_text='For preliminary registration', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ONCOLOGIST', 'SURGEON', 'HEMATOLOGIST', 'PSYCHOLOGIST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked-in'), ('WAITING_TRIAGE', 'Waiting Triage'), ('TRIAGED', 'Triaged'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registry_no',
            field=models.CharField(help_text='Primary unique identifier (National ID or Passport)', max_length=50, unique=True, verbose_name='ID/Passport Number'),
        ),
    ]
