# Generated by Django 6.0.4 on 2026-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_prescription_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
