# Generated by Django 6.0.4 on 2026-06-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_queue_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('side_effects_present', models.TextField(blank=True, default='')),
                ('medications_received', models.TextField(blank=True, default='')),
                ('reason_for_visit', models.JSONField(blank=True, default=dict)),
                ('service_disposition', models.JSONField(blank=True, default=dict)),
                ('discharge_meds_matrix', models.JSONField(blank=True, default=list)),
                ('date_of_next_visit', models.DateField(blank=True, null=True)),
                ('oncologist_name', models.CharField(blank=True, default='DR. WATTANGA L.A.', max_length=255)),
                ('nurse_name', models.CharField(blank=True, default='SR. HELLEN OKELLO', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='core.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='core.registrationrecord')),
            ],
        ),
    ]
