# Generated by Django 6.0.4 on 2026-05-07 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appointment_manual_patient_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ONCOLOGIST', 'SURGEON', 'HEMATOLOGIST', 'PSYCHOLOGIST', 'NURSE', 'LAB_TECH', 'RADIOLOGIST']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
