# Generated by Django 6.0.4 on 2026-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_inventoryitem_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='dosage_form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Oral Suspension'), ('VIAL', 'Vial (Liquid/Powder for Injection)'), ('AMP_INJ', 'Ampoule (Injection)'), ('INF_BAG', 'Infusion Bag (Premixed Cytotoxic/Hydration)'), ('OINTMENT', 'Ointment / Cream'), ('PATCH', 'Transdermal Patch (e.g., Fentanyl Palliative Care)'), ('PESSARY', 'Pessary (e.g., localized hormonal therapies)'), ('SUPPOSITORY', 'Suppository (e.g., antiemetics / palliative comfort care)')], default='TABLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
