# Generated by Django 6.0.4 on 2026-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_icd10diagnosis_primary_site_patientdiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_confirmation_doc',
            field=models.FileField(blank=True, help_text='Bank Confirmation Letter or Cancelled Cheque (PDF)', null=True, upload_to='supplier_compliance/bank_verification/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='incorporation_doc',
            field=models.FileField(blank=True, help_text='Certificate of Incorporation or Registration (PDF)', null=True, upload_to='supplier_compliance/incorporation/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kra_pin_doc',
            field=models.FileField(blank=True, help_text='Uploaded KRA PIN/TIN Document (PDF)', null=True, upload_to='supplier_compliance/kra_pin/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='license_number',
            field=models.CharField(blank=True, help_text='Regulatory Operating License Number (e.g., PPB or County License)', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='regulatory_license_doc',
            field=models.FileField(blank=True, help_text='Valid PPB / Commercial Trade License Document (PDF)', null=True, upload_to='supplier_compliance/licenses/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_compliance_doc',
            field=models.FileField(blank=True, help_text='Valid Tax Compliance Certificate (PDF)', null=True, upload_to='supplier_compliance/tcc/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_compliance_expiry',
            field=models.DateField(blank=True, help_text='Expiry date of the current Tax Compliance Certificate', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tax ID Number / KRA PIN', max_length=50),
        ),
    ]
