# Generated by Django 6.0.4 on 2026-05-07 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_practitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemosession',
            name='pre_auth_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('current_station', models.CharField(choices=[('REGISTRATION', 'Registration'), ('TRIAGE', 'Triage Station'), ('DOCTOR', 'Consultation Room'), ('LAB', 'Laboratory'), ('RADIOLOGY', 'Radiology Room'), ('PSYCHOLOGY', 'Psychology Room'), ('PHARMACY', 'Pharmacy'), ('BILLING', 'Billing/Discharge')], default='TRIAGE', max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Attendance'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal Priority'), ('HIGH', 'High Priority'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='labresult',
            name='queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.queue'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.queue'),
        ),
    ]
