# Generated by Django 6.0.4 on 2026-06-01 12:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_supplier_bank_confirmation_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoice',
            old_name='total_amount',
            new_name='total_billed',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='is_fully_paid',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='delivery_deadline',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_estimated_cost',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid In Full')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 1, 12, 38, 27, 205812, tzinfo=datetime.timezone.utc), help_text='Expected delivery date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 60', 'Net 60')], default='Net 30', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Sent'), ('RECEIVED', 'Goods Received'), ('PARTIAL', 'Partially Received'), ('CLOSED', 'Closed/Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.supplier'),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('delivery_note_ref', models.CharField(help_text='Vendor Delivery Note Number', max_length=100)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('ordered_quantity', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('satisfaction_level', models.CharField(choices=[('GoodCondition', 'Good Condition'), ('Satisfactory', 'Satisfactory'), ('Shortage', 'Shortage / Discrepancy'), ('Damaged', 'Damaged & Rejected')], default='GoodCondition', max_length=30)),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_received', to='core.goodsreceivednote')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('Bank Wire', 'Bank Wire'), ('M-Pesa Corporate', 'M-Pesa Corporate Paybill'), ('Cheque', 'Cheque')], default='Bank Wire', max_length=30)),
                ('payment_reference', models.CharField(help_text='Transaction hash, Cheque No, or M-Pesa Code', max_length=100, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.purchaseinvoice')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('NURSING', 'Nursing'), ('PHARMACY', 'Pharmacy'), ('RADIOLOGY', 'Radiology'), ('LAB', 'Laboratory'), ('MARKETING', 'Marketing'), ('ADMIN', 'Administration')], default='PHARMACY', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder')),
            ],
        ),
    ]
