# Generated by Django 6.0.4 on 2026-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stocktake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-created_at']},
        ),
    ]
