# Generated by Django 6.0.4 on 2026-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bill_bill_no_drug_created_at_protocol_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registry_no',
            field=models.CharField(help_text='National ID or Passport Number', max_length=50, unique=True, verbose_name='ID Number'),
        ),
    ]
