# Generated by Django 6.0.4 on 2026-06-09 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_stocktake_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='executed_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
