# Generated by Django 6.0.4 on 2026-06-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stocktake_executed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktake',
            old_name='executed_at',
            new_name='recorded_at',
        ),
    ]
