# Generated by Django 6.0.4 on 2026-05-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_labinventoryitem_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinventoryitem',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='labinventoryitem',
            name='min_stock',
            field=models.IntegerField(default=5),
        ),
    ]
