# Generated by Django 6.0.4 on 2026-06-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_executed_at_stocktake_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('VIAL', 'Vial'), ('SYRUP', 'Syrup')], max_length=20, null=True),
        ),
    ]
