# Generated by Django 6.0.4 on 2026-06-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_drug_dosage_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='lab_item',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='pharmacy_item',
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='core.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when requisition was submitted'),
        ),
    ]
