# Generated by Django 6.0.4 on 2026-06-09 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_requisitionitem_lab_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SALARIES', 'Salaries'), ('WAGES', 'Wages'), ('LOCUM', 'Locum'), ('TRANSPORT', 'Transport'), ('SECURITY', 'Security & Alarm'), ('MAINTENANCE', 'Maintenance'), ('CATERING', 'Catering'), ('BANK_CHARGES', 'Bank Charges'), ('LICENSING', 'Licensing'), ('MARKETING', 'Marketing'), ('LEGAL_FEES', 'Legal Fees'), ('COMMUNICATION', 'Communication'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities (Water & Elec)')], default='SALARIES', max_length=30)),
                ('behavior', models.CharField(choices=[('Fixed', 'Fixed (Auto-Renewable)'), ('Variable', 'Variable (On-Demand)')], default='Fixed', max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, default='PENDING_SORT', max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='expense_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Voucher',
                'verbose_name_plural': 'Expense Vouchers',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
