# Generated by Django 6.0.4 on 2026-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid to offset expense', max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total expense amount invoiced/due', max_digits=12),
        ),
    ]
